/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: luizfern <lfluiz.lf@gmail.com>             +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/08/09 15:10:45 by luizfern          #+#    #+#             */
/*   Updated: 2021/08/14 18:24:14 by luizfern         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

# include "libftprintf.h"
# include <stdio.h>
int main ()
{
	char* pointer;
	int return_printf;
	char a = 'a';
	char b[] = "teste s";
	pointer = (char*)calloc(sizeof(char), 2);
	pointer[0] = 'a';

	printf("\n\n ---------------FORMAT C TESTS #1------------------ \n\n");
	return_printf = ft_printf("o caracter e: %c", a);
	printf("\n\n");
	printf("Retorno do ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O caracter e: %c", a);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT C TESTS #1------------------ \n\n");
	return_printf = ft_printf("o char %c e igual ao char %c", a, a);
	printf("\n\n");
	printf("Retorno do ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("o char %c e igual ao char %c", a, a);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT S TESTS--------------------- \n\n");
	return_printf = ft_printf("A string e: %s", b);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("A string e: %s", b);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT D TESTS 1--------------------- \n\n");
	return_printf = ft_printf("O numero e: %d", 42);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e: %d", 42);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT D TESTS 2--------------------- \n\n");
	return_printf = ft_printf("O numero %d e diferente do numero %d", 42, 24);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero %d e diferente do numero %d", 42, 24);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT D TESTS 3--------------------- \n\n");
	return_printf = ft_printf("printando numero muiiiito grande 5000000000000: %d", 5000000000000);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("printando numero muiiiito grande 5000000000000: %d", 5000000000000);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT I TESTS 1--------------------- \n\n");
	return_printf = ft_printf("O numero e: %i", 42);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e: %i", 42);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT I TESTS 2--------------------- \n\n");
	return_printf = ft_printf("O numero %i e diferente do numero %i", 42, 24);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero %i e diferente do numero %i", 42, 24);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT I TESTS 3--------------------- \n\n");
	return_printf = ft_printf("printando numero muiiiito grande 5000000000000: %i", 5000000000000);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("printando numero muiiiito grande 5000000000000: %i", 5000000000000);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT I TESTS 4 --------------------- \n\n");
	return_printf = ft_printf("printando numero negativo MIN INT: %i", -2147483648);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("printando numero negativo MIN INT: %i", -2147483648);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT I TESTS 5 --------------------- \n\n");
	return_printf = ft_printf("MIN NEGATIVO -1: %i", -2147483649);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("MIN NEGATIVO -1: %i", -2147483649);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT I TESTS 6 --------------------- \n\n");
	return_printf = ft_printf("printando MAX INT : %i", 2147483647);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("printando MAX INT : %i", 2147483647);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT I TESTS 7 --------------------- \n\n");
	return_printf = ft_printf("printando MAX INT + 1 : %i", 2147483648);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("printando MAX INT + 1 : %i", 2147483648);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT U TESTS --------------------- \n\n");
	return_printf = ft_printf("O numero e %u", 42);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %u", 42);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT U TESTS 2 --------------------- \n\n");
	return_printf = ft_printf("O numero e %u", 0);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %u", 0);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT U TESTS 3 --------------------- \n\n");
	return_printf = ft_printf("O numero e %u", -1);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %u", -1);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT U TESTS 4 --------------------- \n\n");
	return_printf = ft_printf("O numero e %u", 10);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %u", 10);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT U TESTS 5 --------------------- \n\n");
	return_printf = ft_printf("O numero e %u", 8);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %u", 8);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT U TESTS 6 --------------------- \n\n");
	return_printf = ft_printf("O numero e %u", 42949672951);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %u", 42949672951);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT U TESTS 7 --------------------- \n\n");
	return_printf = ft_printf("O numero e %u", 5000000000000000000000);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %u", 5000000000000000000000);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n ---------------FORMAT x min TEST 1 --------------------- \n\n");
	return_printf = ft_printf("O numero e %x", pointer);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %x", pointer);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	printf("\n\n ---------------FORMAT x min TEST 2 --------------------- \n\n");
	return_printf = ft_printf("O numero e %x", 764);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %x", 764);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	printf("\n\n ---------------FORMAT x min TEST 3 --------------------- \n\n");
	return_printf = ft_printf("O numero e %x", 10);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %x", 10);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	printf("\n\n ---------------FORMAT x min TEST 4 --------------------- \n\n");
	return_printf = ft_printf("O numero e %x", 5051);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %x", 5051);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	printf("\n\n ---------------FORMAT X min TEST 1 --------------------- \n\n");
	return_printf = ft_printf("O numero e %X", pointer);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %X", pointer);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	printf("\n\n ---------------FORMAT X min TEST 2 --------------------- \n\n");
	return_printf = ft_printf("O numero e %X", 764);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %X", 764);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	printf("\n\n ---------------FORMAT X min TEST 3 --------------------- \n\n");
	return_printf = ft_printf("O numero e %X", 10);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %X", 10);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	printf("\n\n ---------------FORMAT X min TEST 4 --------------------- \n\n");
	return_printf = ft_printf("O numero e %X", 5051);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %X", 5051);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	printf("\n\n ---------------FORMAT P TEST 1 --------------------- \n\n");
	return_printf = ft_printf("O numero e %p", 5051);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %p", 5051);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	printf("\n\n ---------------FORMAT P TEST 2 --------------------- \n\n");
	return_printf = ft_printf("O numero e %p", pointer);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %p", pointer);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	printf("\n\n ---------------FORMAT P TEST 3 --------------------- \n\n");
	return_printf = ft_printf("O numero e %p", 764);
	printf("\n\n");
	printf("Retorno da ft_printf: %d", return_printf);
	printf("\n\n");
	return_printf = printf("O numero e %p", 764);
	printf("\n\n");
	printf("Retorno da printf: %d", return_printf);
	printf("\n\n");
	free(pointer);
}
