name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  norminette:

    runs-on: ubuntu-latest
    container:
      image: tawliew/norminette:latest
      options: -v /__w/ft_printf:/code
    steps:
      - uses: actions/checkout@v2
      - name: test norminette
        run: |
          pwd
          ls -l
